### PR TITLE
Add Server Main and pom.xml

### PR DESCRIPTION
**Pull request by MathewLG**

### CODE REVIEW

**Review by tucosh — COMMENTED** [review]
This is good, the pom.xml seems fine. Unfortunately the project doesn't compile for me ("mvn exec:java") because NewTaskServlet is in a file called NewAdviceServlet.java - can you fix that? (ie rename the file). Then everything should compile with your pom

**Comment by tucosh** [comment]
Better.. it compiles now, but on startup I get this error:

java.lang.IllegalStateException: Multiple servlets map to path /new-advice: com.google.servlets.NewTaskServlet[mapped:ANNOTATION:com.google.servlets.NewTaskServlet],com.google.servlets.NewAdviceServlet[mapped:ANNOTATION:com.google.servlets.NewAdviceServlet]

can you see why that is?

**Comment by nnooney** [comment]
I've confirmed that the latest commit (52d5e60) compiles and I'm able to preview it on my local instance.

**Review by nnooney — APPROVED** [review]
LGTM

**Pull request merged**
